import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AntdProvider from '@/component/AntdProvider'
import ReduxProvider from '@/component/reduxProvider'
import './../styles/antdOverride.css'
import './../styles/commonClasses.css'
import './../styles/layout.css'
import './../styles/loader.css'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Inventory Management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet"/>
      </head>
      <body className={inter.className}>
        <ReduxProvider>
          <AntdProvider>
            {children}
          </AntdProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
