import type { Metadata } from "next";
import "./globals.css";
import AntdProvider from "@/component/AntdProvider";
import ReduxProvider from "@/component/reduxProvider";
import "./../styles/antdOverride.css";
import "./../styles/commonClasses.css";
import "./../styles/layout.css";
import "./../styles/loader.css";
import React from "react";

export const metadata: Metadata = {
  title: "Inventory Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-900 text-white">
        <ReduxProvider>
          <AntdProvider>{children}</AntdProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
